name: Deploy to Loggernet

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Loggernet
        env:
          SUPER_SECRET: '1oreSegreg8'
        run: |
          sshpass -p "$SUPER_SECRET" rsync -av --delete --rsh="ssh -o StrictHostKeyChecking=no" . marc@192.168.115.73:/var/www/html/
